import express from 'express';
const router = express.Router();

import admin from './admin.routes.js';
router.use('/admin', admin);
import alerts from './alerts.routes.js';
router.use('/alerts', alerts);
import allocate from './allocate.routes.js';
router.use('/allocate', allocate);
import auth from './auth.routes.js';
router.use('/auth', auth);
import contactRequests from './contactRequest.routes.js';
router.use('/contactRequests', contactRequests);
import farmers from './farmer.routes.js';
router.use('/farmers', farmers);
import feedback from './feedback.routes.js';
router.use('/feedback', feedback);
import feedbackUX from './feedbackUX.routes.js';
router.use('/feedbackUX', feedbackUX);
import harvests from './harvest.routes.js';
router.use('/harvests', harvests);
import hives from './hive.routes.js';
router.use('/hives', hives);
import inspections from './inspection.routes.js';
router.use('/inspections', inspections);
import ndvi from './ndvi.routes.js';
router.use('/ndvi', ndvi);
import requests from './request.routes.js';
router.use('/requests', requests);
import score from './score.routes.js';
router.use('/score', score);
import simulate from './simulate.routes.js';
router.use('/simulate', simulate);
import suggestions from './suggestion.routes.js';
router.use('/suggestions', suggestions);
import sync from './sync.routes.js';
router.use('/sync', sync);
import tileRoutes from './tile.routes.js';
router.use('/tileRoutes', tileRoutes);
import trace from './trace.routes.js';
router.use('/trace', trace);

export default router;
